### ISSUE TITLE
Issue with say() command

### ISSUE THREAD

**Issue by novyapp** [hyansuper/rcute-cozmars#25]
Hey there!

First of all, thank you for this amazing project! A had so much fun getting everything together. Now I'm in the stage where I'm trying to get the whole software get to run and sadly I have some issues with say() command. Here is what I get while trying to use it:

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_cozmars\robot.py", line 355, in _run_loop
    t.cancel()
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\wsmprpc\client.py", line 33, in cancel
    self._cancel_task = asyncio.create_task(self._cancel(self._msgid))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 381, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py:934: RuntimeWarning: coroutine 'RPCClient._send_cancel' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "C:/Users/micno/PycharmProjects/pythonProject1/test.py", line 4, in <module>
    robot.say("hello")
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_cozmars\util.py", line 42, in new_func
    return fut.result(kwargs.pop('timeout', None))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_cozmars\robot.py", line 267, in say
    wav_data = await asyncio.get_running_loop().run_in_executor(None, functools.partial(self._tts.tts_wav, txt, **options))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_ai\tts_pyttsx3.py", line 34, in tts_wav
    with tempfile.NamedTemporaryFile(suffix='.wav') as f:
NameError: name 'tempfile' is not defined
Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<EyeAnimation.animate() running at C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_cozmars\eye_animation.py:243> wait_for=<RPCFuture pending cb=[RPCFuture.__init__.<locals>.<lambda>() at C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\wsmprpc\client.py:22, <TaskWakeupMethWrapper object at 0x0000020B29E5C2B0>()]>>
Exception ignored in: <function RPCFuture.__del__ at 0x0000020B07F91430>
Traceback (most recent call last):
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\wsmprpc\client.py", line 37, in __del__
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\wsmprpc\client.py", line 33, in cancel
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 381, in create_task
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'RPCClient._send_cancel' was never awaited

when I add "import tempfile" in tts_pyttsx3.py i'm getting something like this:

> Traceback (most recent call last):
  File "C:/Users/micno/PycharmProjects/pythonProject1/test.py", line 4, in <module>
    robot.say("hello")
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_cozmars\util.py", line 42, in new_func
    return fut.result(kwargs.pop('timeout', None))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 444, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "C:\Users\micno\PycharmProjects\pythonProject1\venv\lib\site-packages\rcute_cozmars\robot.py", line 268, in say
    with wave.open(io.BytesIO(wav_data)) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\wave.py", line 510, in open
    return Wave_read(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\wave.py", line 164, in __init__
    self.initfp(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\chunk.py", line 63, in __init__
    raise EOFError
EOFError

Here is code what I'm using:

> `from rcute_cozmars import Robot
with Robot('192.168.0.150') as robot:
    robot.say("hello")`

thank you in advance for your help!

**Comment by hyansuper** [comment]
does other functions work well? if so, try examples of https://github.com/nateshmbhat/pyttsx3

**Comment by novyapp** [comment]
I didn't test all of them yet.

About pyttsx3. If I import it directly to .py file and save the ".wav" first on PC it works.

So I'm guessting the issue might be somewhere in tempfile. 

My working example:
```
import pyttsx3
import rcute_ai as ai
from rcute_cozmars import Robot


with Robot('192.168.0.150') as robot:
    engine = pyttsx3.init()
    string =input(f"Say:")
    engine.setProperty('rate', 100)
    voices = engine.getProperty('voices')
    engine.setProperty('voice', voices[2].id)
    engine.save_to_file(string, 'speech.wav')
    engine.runAndWait()
    robot.speaker.play('./speech.wav')
```

**Comment by hyansuper** [comment]
I can't help you debug exactly the problem, but I think you've narrowed it down.
the say() api expands to something like below, you can run it and find what the problem.
```
with Robot('192.168.0.150') as robot:
    engine = pyttsx3.init()
    string =input(f"Say:")

    op=robot.env.vars.get('say', {}).get(system(), {}).copy()
    for k,v in op.items():
        engine.setProperty(k, v)

    with tempfile.NamedTemporaryFile(suffix='.wav') as tmpfile:
        engine.save_to_file(string, tmpfile.name)
        engine.runAndWait()
        tmpfile.seek(0)
        wav_data=tmpfile.read()
        with wave.open(io.BytesIO(wav_data)) as f:
            robot.speaker.play(f.readframes(f.getnframes()), repeat=repeat, volume=robot.env.vars.get('say_vol'), 
sample_rate=f.getframerate(), dtype='int16')
```
